---
title: Mgtr. Víctor Gauto
format:
  typst: 
    title: ""
    papersize: a4
    margin:
      x: 1cm
      y: 1cm
    mainfont: "Lato"
    font-paths: fuentes
execute: 
  output: asis
  eval: true
  warning: false
  echo: false
editor_options: 
  chunk_output_type: console
extensions:
  iconify:
    set: "octicon"
    size: "lg"
    inline: true
    mode: "svg"
    style: "color: #00AF50;"
---

```{r}
source("scripts/soporte.R")
```

```{=typst}
#set par(
  justify: false
)

#set page(
  footer: context [
    #text(fill: gray, size: .8em)[
    Versión online: #link("https://vhgauto.github.io/cv/")[
      https://vhgauto.github.io/cv/
    ]
    #h(1fr)
    #counter(page).display(
      "1 de 1",
      both: true
      )
    ]
  ]
)

#import "@preview/fontawesome:0.6.0": *

#show link: set text(fill: rgb("#00AF50"), weight: "regular")

#show list: set list(marker: [#text(fill: rgb("#00AF50"))[▸]], body-indent: 0pt)

#show heading: it => pad(
  left: 20pt, bottom: 10pt, text(font: "Rufina", fill: rgb("#00AF50"), size: 1.5em)[#upper[#it]]
)

#show underline: set underline(stroke: rgb("#00AF50"))

#let kw(term) = rect(stroke: rgb("#00AF50"))[#text(size: .8em)[#term]]

#let barra = text(fill: rgb("#00AF50"), weight: "bold")[ | ]

#let mono(term) = text(font: "Fira Code", weight: "regular")[#term]

#let tit(term, inicio, fin) = {
  text(font: "Rufina", size: 1.5em)[#upper[#term]] 
  text(size: .9em)[\ #fa-icon("calendar", solid: true, fill: rgb("#00AF50")) #h(.2cm) #inicio ▸ #fin]
}

#let detalle(titulo, lugar, contenido) = {
  text(weight: "bold")[#titulo. #h(.1cm)] 
  [#fa-icon("location-dot", solid: true, fill: rgb("#00AF50")) #lugar. \ #contenido.]
}

#let encabezado(tit) = text(font: "Rufina", size: 1.5em)[#upper[#tit]]
```

```{=typst}
#rect(
  width: 100%,
  fill: rgb("#00AF50"),
  inset: 1em,
)[
  #align(left)[
    #text(fill: white, font: "Rufina")[
      #text(size: 1.5em)[Mgtr.] #h(1em)
      #text(size: 3em)[Víctor Gauto] #h(1em)
      #text(size: 1.5em)[Ingeniero Químico]

    ]
  ]
]
```

```{=typst}
#grid(
  columns: (25%, 45%, 30%),
  gutter: 10pt,
  [#align(right)[Fecha de nacimiento]],
  [`{r} format(nacimiento, "%d/%b/%Y")` (`{r} floor(as.numeric(Sys.Date() - nacimiento)/365)` años)],
  grid.cell(
    colspan: 1,
    rowspan: 5,
    align: left,
    rect(
      image("img/foto.jpg", width: 70%),
      stroke: 4pt + rgb("#00AF50"),
      inset: 0pt
    ),
  ),
  [#align(right)[Correo electrónico]],
  [#link("mailto:victor.gauto@ca.frre.utn.edu.ar")[victor.gauto\@ca.frre.utn.edu.ar]],
  [#align(right)[Redes sociales]],
  [
    #link("https://x.com/vhgauto")[#fa-icon("twitter", solid: true)] #h(.2cm)
    #link("https://github.com/vhgauto")[#fa-icon("github", solid: true)] #h(.2cm)
    #link("https://www.instagram.com/vhgauto/")[#fa-icon("instagram", solid: true)] #h(.2cm) / vhgauto
  ],
  [#align(right)[Investigación]],
  [
    #link("https://orcid.org/0000-0001-9960-8558")[#fa-icon("orcid") ORCID] #h(.1cm) | #h(.1cm)
    #link("https://scholar.google.es/citations?user=nxCfD0AAAAAJ")[Google Scholar] #h(.1cm) | #h(.1cm)
    #link("https://www.researchgate.net/profile/Victor_Gauto")[Research Gate]
  ],
  [#align(right)[Sitio web]],
  [#link("https://vhgauto.github.io/")[https://vhgauto.github.io/]]
)
```

```{=typst}
#align(center)[
  #table(
  columns: (auto, auto, auto, auto),
  [#kw[data science]], [#kw[data visualization]], [#kw[GIS]], [#kw[machine learning]], [#kw[maps]], [#kw[remote sensing]], [#kw[Rstats]], [#kw[water quality]]
)
]
```

# Posición actual

Estudiante del **Doctorado en Geomática y Sistemas Espaciales** del [Instituto de Altos Estudios Espaciales Mario Gulich](https://ig.conae.unc.edu.ar/), dependiente de la [Comisión Nacional de Actividades Espaciales](https://www.argentina.gob.ar/ciencia/conae) y la [Universidad Nacional de Córdoba](https://www.unc.edu.ar/). Tema de tesis “Desarrollo de un modelo predictivo de indicadores de calidad de agua en la cuenca media del río Paraná mediante técnicas de teledetección satelital y aprendizaje automático”.

Becario doctoral CONICET, en el [Instituto de Investigación para el Desarrollo Territorial y del Hábitat Humano](https://iidthh.conicet.gov.ar/).

Integrante del [Grupo de Investigación Sobre Temas Ambientales y Químicos](https://www.instagram.com/gistaq.utn/) en la [Universidad Tecnológica Nacional, Facultad Regional Resistencia](https://www.frre.utn.edu.ar/).

# Educación

```{=typst}
#grid(
  columns: (25%, 75%),
  gutter: 10pt,
  [#tit([Doctorado], [Abr/2022], [En proceso])],
  [#detalle(
    [Doctorado en Geomática y Sistemas Espaciales], 
    [Instituto Gulich],
    [#underline[Tesis]: Desarrollo de un modelo predictivo de indicadores de calidad de agua en la cuenca media del río Paraná mediante técnicas de teledetección satelital y aprendizaje automático]
  )],
  [#tit([Maestría], [Feb/2020], [Sep/2023])],
  [#detalle(
    [Maestría en Aplicaciones de Información Espacial], 
    [Instituto Gulich],
    [#underline[Tesis]: Caracterización óptica de aguas superficiales a partir de imágenes satelitales multi e hiperespectrales en la región de Gran Resistencia, Chaco]
  )],
  [#tit([Maestría], [Mar/2017], [Feb/2019])],
  [#detalle(
    [Maestría en Ingeniería Química y Biomolecular], 
    [Sogang University, Seúl, Corea del Sur],
    [#underline[Tesis]: Catalizadores de cobalto con soporte de alúmina mesoporosa ordenada para síntesis de Fischer-Tropsch. Promedio: 9,8/10]
  )],
  [#tit([Universidad], [Mar/2007], [Dic/2014])],
  [#detalle(
    [Ingeniería Química], 
    [Universidad Tecnológica Nacional (UTN), Facultad Regional Resistencia (FRRe)],
    [Promedio: 7,2/10. Título intermedio: Técnico Universitario Químico (2012)]
  )]
)
```

# Experiencia

```{=typst}
#grid(
  columns: (25%, 75%),
  gutter: 10pt,
  [#tit([Investigación], [Feb/2023], [En proceso])],
  [#detalle(
    [Grupo de Investigación Sobre Temas Ambientales y Químicos], 
    [UTN FRRe],
    [#underline[Proyecto]: Estimar indicadores de calidad de agua en la cuenca media del Río Paraná para el desarrollo de un algoritmo mediante técnicas de teledetección satelital. #link("https://vhgauto.quarto.pub/gistaq-parana/")[Link #fa-icon("link")]]
  )],
  [#tit([Investigación], [Feb/2021], [Feb/2023])],
  [#detalle(
    [Grupo de Investigación Sobre Temas Ambientales y Químicos], 
    [UTN FRRe],
    [#underline[Proyecto]: Caracterización fisicoquímica de cuerpos de aguas continentales para la evaluación de la utilización de algoritmos en el monitoreo satelital de la calidad del agua]
  )],
  [#tit([Pasantía], [Mar/2022], [Sep/2022])],
  [#detalle(
    [Instituto de Detección Electromagnética del Ambiente], 
    [Consejo Nacional de Investigación, Milán, Italia],
    [Uso de producto hiperespectral para estudio de lagunas y ríos]
  )],
  [#tit([Servicios], [May/2019], [Feb/2020])],
  [#detalle(
    [Grupo de Investigación Sobre Temas Ambientales y Químicos], 
    [UTN FRRe],
    [Análisis de calidad de agua y autocalentamiento de carbón. Análisis fisicoquímicos de laboratorio. Gestión de personal, contabilidad y clientes]
  )],
  [#tit([Investigación], [May/2019], [Feb/2020])],
  [#detalle(
    [Grupo de Investigación Sobre Temas Ambientales y Químicos], 
    [UTN FRRe],
    [#underline[Proyecto]: Determinación del fenómeno de sorción-desorción de colorantes en materiales de bajo costo estudiados en un reactor tubular de lecho fijo]
  )],
  [#tit([Investigación], [May/2017], [Feb/2019])],
  [#detalle(
    [Laboratorio de Ingeniería de las Reacciones y Catálisis a Nanoescala], 
    [Sogang University, Seúl, Corea del Sur],
    [#underline[Área]: Tecnología gas-líquido, síntesis de Fischer-Tropsch. Síntesis de catalizadores. Puesta en marcha y manipulación de reactor heterogéneo]
  )],
  [#tit([Auxiliar Docente], [Sep/2015], [Feb/2017])],
  [#detalle(
    [Actividad en Docencia], 
    [Universidad Tecnológica Nacional, Facultad Regional Resistencia],
    [Auxiliar docente con dedicación simple en dos cátedras: Fisicoquímica (Ingeniería Química) y Química (Ingeniería en Sistemas de Información)]
  )]
)
```
# Publicaciones

```{=typst}
#grid(
  columns: (25%, 75%),
  gutter: 10pt,
  [#encabezado([2025])],
  [- Víctor Gauto, Enid Utges, Elsa Hervot, Maria Daniela Tenev, and Alejandro Farías. #text(weight: "bold")[“Turbidity Estimation by Machine Learning Modelling and Remote Sensing Techniques Applied to a Water Treatment Plant.”] Journal of Sustainable Development of Energy, Water and Environment Systems 13, no. 2 (2025): 1-17. #link("https://doi.org/10.13044/j.sdewes.d13.0539")[10.13044/j.sdewes.d13.0539 #fa-icon("link")]],
  [#encabezado([2024])],
  [- Sofía Paná, Matías Bonansea, Vera Camacho Valdéz, Inés del Valle Asís, Víctor Gauto, and Anabella Ferral. #text(weight: "bold")[“Modelling of Phosphorus and Nitrogen Delivery in a Strategic River Basin.”] Journal of Sustainable Development of Energy, Water and Environment Systems 13, no. 2 (2025): 1-17. #link("https://doi.org/10.1109/ARGENCON62399.2024.10735960")[10.1109/ARGENCON62399.2024.10735960 #fa-icon("link")]
  
  - Víctor Gauto, Enid Marta Utgés, Elsa Ivonne Hervot, María Daniela Tenev, Alejandro Farías, Matías Bonansea, and Anabella Ferral. #text(weight: "bold")[“Remote Sensing Regression Models to Estimate Water Quality Indicators in Continental Waters in North-East Argentina.”] In 2024 IEEE Biennial Congress of Argentina (ARGENCON), pp. 1-6. IEEE, 2024. #link("https://doi.org/10.1109/ARGENCON62399.2024.10735875")[10.1109/ARGENCON62399.2024.10735875 #fa-icon("link")],
  
  - Matias Bonansea, Sofia Gutierrez, Mariana Correa, Sofia Pana, Víctor Gauto, Francisco Nemiña, Alba Germán, Giuliana Beltramone, Lucio Pinotti, and Anabella Ferral. #text(weight: "bold")[“Comparison of water surface temperature retrieval methods from Landsat 9 satellite data.”] The International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences 48 (2024): 1-6. #link("https://doi.org/10.5194/isprs-archives-XLVIII-2-W6-2024-1-2024")[10.5194/isprs-archives-XLVIII-2-W6-2024-1-2024 #fa-icon("link")],
  
  - Rossana, Villalba, Anabella Ferral, Julián Baéz, Jorge Kurita, Víctor Gauto, and Juan Carlos Bertoni. #text(weight: "bold")[“Spatio-temporal characterization of precipitation in the Middle and Lower Paraguay Basin based on satellite products and weather station data.”] The International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences 48 (2024): 65-71. #link("https://doi.org/10.5194/isprs-archives-XLVIII-2-W6-2024-65-2024")[10.5194/isprs-archives-XLVIII-2-W6-2024-65-2024 #fa-icon("link")]],

  [#encabezado([2023])],
  [- María Daniela Tenev, Camila Torre, Gimena Fontana, Víctor Gauto, Mario Sergio Cleva, Néstor Caracciolo, and Susana Boeykens. #text(weight: "bold")[“Studies of Adsorption-Desorption of Methylene Blue in a Fixed-Bed Reactor Filled with Cotton and Tanine Industry Waste.”] LACCEI 1, no. 8 (2023). #link("https://doi.org/10.18687/LACCEI2023.1.1.1594")[10.18687/LACCEI2023.1.1.1594 #fa-icon("link")]

  - Sofia Pana, Víctor Gauto, Mattia Terzaghi, Anabella Ferral, Fransisco Nemiña, Inés del Valle Asís, and Matías Bonansea. #text(weight: "bold")[“Changes in land covers in two river basins in central argentina region. monitoring the sdg 15.3. 1 indicator.”] In 2023 XX Workshop on Information Processing and Control (RPIC), pp. 1-6. IEEE, 2023. #link("https://doi.org/10.1109/RPIC59053.2023.10530795")[10.1109/RPIC59053.2023.10530795 #fa-icon("link")]],

  [#encabezado([2022])],
  [- Víctor Gauto, Anabella Ferral, Matias Bonansea, Alejandro Farías, Marcelo Scavuzzo, Osvaldo Cardozo, Alba German, and Claudia Giardino. #text(weight: "bold")[“First results of PRISMA satellite data applied to water quality monitoring in Argentina.”] In 2022 IEEE Biennial Congress of Argentina (ARGENCON), pp. 1-8. IEEE, 2022. #link("https://doi.org/10.1109/ARGENCON55245.2022.9939810")[10.1109/ARGENCON55245.2022.9939810 #fa-icon("link")]],

  [#encabezado([2016])],
  [- Tenev, Daniela, Alejandro R. Farías, Enrique E. Utgés, Víctor Gauto, Gastón Lara, Camila Torre, Sofía Romero, and Gonzalo Dos Santos. #text(weight: "bold")[“Instalación de un biodigestor y efecto de la adición de biofertilizante en la germinación de semillas de lechuga (Lactuca sativa L).”] (2016).]
)
```

# Cursos

```{=typst}
#grid(
  columns: (25%, 75%),
  gutter: 10pt,
  [#encabezado([2025])],
  [
    - Caracterización hiperespectral: Una introducción a las técnicas de laboratorio, mediciones de campo e información satelital.
    - Escuela de Primavera: Inteligencia artificial y computación cuántica en la observación de la Tierra.
  ],

  [#encabezado([2024])],
  [- Redes neuronales.],

  [#encabezado([2023])],
  [- Teleobservación de aguas marinas, costeras e interiores.],

  [#encabezado([2021])],
  [
    - Introducción a Sistemas de Información Geográfica y Teledetección con Orientación a la Gestión Territorial.
    - Beyond the Visible Introduction to Hyperspectral Remote Sensing.
    - Mapping soil moisture and inundation at high resolution.
    - Air quality and climate processes using satellites and atmospheric models.
    - Wildfire prevention, monitoring and damage assessment.
    - Retrieval of biophysical parameters from optical and radar data.
    - Hyperspectral data processing.
    - Processing of SAR images: integration of multi-frequency polarimetric SAR and optical data for land cover classification and creation of thematic maps.
    - SAR differential interferometry and tomography.
    - Machine learning in remote sensing.
    - Earth Engine laboratory.
  ],

  [#encabezado([2019])],
  [
    - Escuela de monitoreo ambiental: de la nanociencia a la teledetección. Nuevos paradigmas de participación ciudadana.
    - Gestión de la ciencia, la tecnología y la innovación.
  ],

  [#encabezado([2016])],
  [- Desarrollando proyectos de I+D+i.],

  [#encabezado([2015])],
  [
    - Curso-taller teórico práctico “Generación de Biogás y Abono a partir de Residuos Orgánicos”.
    - Introducción a la investigación, el desarrollo y la innovación.
  ]
)
```

# Habilidades

```{=typst}
#grid(
  columns: (25%, 75%),
  gutter: 10pt,
  [#encabezado([Datos])],
  [
    - #underline[Procesamiento]: lectura, manipulación y almacenamiento. Creación y análisis de figuras.
    - #underline[Modelado]: regresión y clasificación. Tradicionales y de aprendizaje automático. Redes neuronales. Métricas de desempeño.
    - #underline[Figuras]: creación, interpretación y estilos personalizados.
  ],

  [#encabezado([Geografía])],
  [
    - #underline[Análisis de datos]: lectura, procesamiento y modelado de datos geográficos.
    - #underline[Visualización]: ráster y vectores, creación de mapas, estilos personalizados.
    - #underline[Datos satelitales]: búsqueda, obtención y lectura de datos provenientes de plataformas satelitales.
  ],

  [#encabezado([Programación])],
  [#mono[R] #barra #mono[Python] #barra #mono[Quarto] #barra #mono[LaTeX] #barra #mono[Typst] #barra #mono[git] #barra #mono[GitHub]],

  [#encabezado([Software])],
  [#mono[RStudio] #barra #mono[QGIS] #barra #mono[Visual Studio Code] #barra #mono[Google Earth Engine] \ #mono[Word] #barra #mono[Excel] #barra #mono[PowerPoint]]
)
```

# Idiomas

```{=typst}
#grid(
  columns: (25%, 75%),
  gutter: 10pt,
  [#encabezado([Inglés])],
  [*Nivel avanzado*. Examen TOEIC: 865/990 (87%). #fa-icon("calendar", fill: rgb("#00AF50")) Nov/2014.],

  [#encabezado([Coreano])],
  [*Nivel básico*. Yonsei University, curso online. #fa-icon("calendar", fill: rgb("#00AF50")) Oct/2020.]
)
```

```{=typst}
#v(100pt)

#align(center)[
  #text(fill: gray)[
    #link("https://github.com/vhgauto/cv")[Ver en #fa-icon("github")] \
    Creado con  #link("https://quarto.org/")[Quarto] y  #link("https://www.r-project.org/")[R] \
    `{r} format(Sys.time(), "%Y-%m-%d")`
  ]
]
```
